### ISSUE TITLE
about ERP

### ISSUE THREAD

**Issue by zhanglei9203** [Emotiv/cortex-v2-example#11]
now as I have the access to emotivePRO and its raw EEG, I face the problem of sending the signal from Matlab to emotivePRO raw eeg in order to mark the input events. I wrote visual stimulus interface in Matlab (psychtoolbox), namely SSVEP/ERP. Thus I need to send data through matlab to emotivePro so that the raw data can be marked markers. Only the raw data with marker can be for further processing, such as superposition, ophthalmogram removal, filtering and so on. So how can I solve this problem.

**Comment by bchaperon** [comment]
Hello @zhanglei9203 
The [EMOTIV customer support](https://www.emotiv.com/contact-support/) should be able to help you with this issue.
