### ISSUE TITLE
C# example getDetectionInfo?

### ISSUE THREAD

**Issue by AdityaSher** [Emotiv/cortex-v2-example#18]
I am not able to find C# code for `getDetectionInfo()` can someone please help me

**Comment by bchaperon** [comment]
Hello @AdityaSher 
The source code for this method is in [CtxClient.cs, line 759](https://github.com/Emotiv/cortex-v2-example/blob/aa86d0a3077d8a501db0ea79d745cd6b3cf0beb2/csharp/CortexAccess/CtxClient.cs#L759).

**Comment by AdityaSher** [comment]
ok thankyou very much.
