### ISSUE TITLE
Request: Unity C# examples

### ISSUE THREAD

**Issue by AdityaSher** [Emotiv/cortex-v2-example#21]
Can we get examples for Unity similar to the ones that we had for the community SDK, just the connection part at least and generic commands like connecting to the headset on the using buttons?

**Comment by hoangphamemotiv** [comment]
we had a example : https://github.com/Emotiv/community-sdk/tree/master/examples_basic/Unity/MentalCommand
i think it has connection part, right?

**Comment by hoangphamemotiv** [comment]
@AdityaSher 
we haven't supported examples for Unity yet. at the moment, you can take a look on C# examples

**Comment by JorgeVelez** [comment]
> Can we get examples for Unity similar to the ones that we had for the community SDK, just the connection part at least and generic commands like connecting to the headset on the using buttons?

I tested it with unity and it works fine, just copy the dlls and use the program.cs files in each demo. You just have to change the "main" method to "start".

**Comment by hoangphamemotiv** [comment]
hi @JorgeVelez . 
did you talk about Cortex example or old SDK Unity example?

**Comment by JorgeVelez** [comment]
Im talking about the new cortex v2 sdk. The csharp code almost works as is in Unity.

**Comment by hoangphamemotiv** [comment]
wow, this is good news. i haven't tried it with Unity yet.  your information very useful. 
thank @JorgeVelez !

**Comment by hoangphamemotiv** [comment]
@JorgeVelez can you share detail the way you make the Cortex working on Unity. it is help other user working on it before we support it.
