### ISSUE TITLE
error code: 32019 message:Session limit on this device has been reached

### ISSUE THREAD

**Issue by AdityaSher** [Emotiv/cortex-v2-example#22]
I have already paid for the pro Version of Emotiv and registered for the EmotivProAPI I am still facing this error, is there any solution?

**Comment by AdityaSher** [comment]
The issue occurred due to missing method="subscribe" the keyword subscribe is missing while **creating a session** in the **cortex v2 docs** (in my case)

**Comment by bchaperon** [comment]
Hi @AdityaSher 
Sorry, I will fix it.
If you notice other errors in the Cortex v2 doc, please don't hesitate to create a ticket.
Thanks for your help :)
