### ISSUE TITLE
Mental Command example for c#

### ISSUE THREAD

**Issue by JorgeVelez** [Emotiv/cortex-v2-example#23]
Hi, I can't seem to find a mental command stream example for C#, but I see one for c++. Is there a reason it's not implemented?

**Comment by bchaperon** [comment]
Hi @JorgeVelez 
Yes, we are missing an example for the mental command stream.
You can probably modify the motion stream example and make return the MC instead of the motion.
Maybe @tungntEmotiv can help you :)

**Comment by JorgeVelez** [comment]
I already did it Benoit, the api is very easy to use. I just thought there was a reason and it couldnt be implemented now.
