### ISSUE TITLE
Replicating power band data

### ISSUE THREAD

**Issue by ollaff** [Emotiv/cortex-v2-example#24]
I'm attempting to replicate the power band data provided from the headset using my own operations. I was wondering what the required steps were in detail. My current steps are as follows:

1. Apply hanning window to eeg data (2 second epoch, updated 8 times a second).
2. calculate fft of the eeg data
3. Square (abs(fft) / fft.size) to get PSD estimate
4. calculate each power band by summing relevant fft buckets
-Each range includes the higher value but not the lower (theta 4-7.99, alpha 8 - 11.99)
-Theta 4-8
-alpha 8-12
-betaL 12-16
-betaH 16-25
-gamma 25-45

Following this process my results aren't consistent with the power band data provided. They are much higher values and don't follow the same pattern (betaH might be higher than betaL in my data but much lower in the provided data).

**Comment by bchaperon** [comment]
Hi @ollaff 
Before applying the Hanning window, you should apply a high pass filter, and remove the mean value for each EEG channel.
