### ISSUE TITLE
Error -32019 message Session limit on this device has been reached.

### ISSUE THREAD

**Issue by temolzin** [Emotiv/cortex-v2-example#45]
I'm programming with C #
with the examples that come in CORTEXUI2
But I couldn't resolve the error Received: Session limit on this device has been reached.
MessageErrorRecieved: code -32019 message Session limit on this device has been reached.
In the config file I don't have anything in LicenseId,
  In DebitNumber I set the value 0.

And I could not solve the error.

**Comment by shung1209** [comment]
I get  **-32019 message Session limit on this device has been reached** on every examples even i edited the debit to 100 even to 200. This is really getting frustrating cause there is not really a clear document how to deal with this.

**Comment by nguoithichkhampha** [comment]
@shung1209 Can you send me request/response to/from Cortex ?

**Comment by shung1209** [comment]
this is what is shown in the command.

EEG LOGGER
Please wear Headset with good signal!!!
Send getUserLogin
Press Esc to exit
handleResponse: getUserLogin
Send hasAccessRight
handleResponse: hasAccessRight
Send authorize
handleResponse: authorize
Authorize successfully.
FindHeadset
Send queryHeadsets
handleResponse: queryHeadsets
Send createSession
Received: Session limit on this device has been reached.
MessageErrorRecieved :code -32019 message Session limit on this device has been reached.

**Comment by nguoithichkhampha** [comment]
I meant the details of request/response to Cortex. I want to see the input params.

**Comment by shung1209** [comment]
May i ask where do i get that? I am so confused.

**Comment by nguoithichkhampha** [comment]
https://github.com/Emotiv/cortex-v2-example/blob/master/csharp/CortexAccess/CtxClient.cs
this class uncomment line 164 and 177

**Comment by temolzin** [comment]
I uncomment line 164 and 177

This is my screen.

[cid:71051cd5-9212-4d06-86f8-ead4abfc777f]
________________________________
De: Cuong Trinh Manh <notifications@github.com>
Enviado: miércoles, 2 de octubre de 2019 03:31 a. m.
Para: Emotiv/cortex-v2-example <cortex-v2-example@noreply.github.com>
CC: temolzin <temolzin@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Emotiv/cortex-v2-example] Error -32019 message Session limit on this device has been reached. (#45)


https://github.com/Emotiv/cortex-v2-example/blob/master/csharp/CortexAccess/CtxClient.cs
this class uncomment line 164 and 177

**Comment by shung1209** [comment]
![image](https://user-images.githubusercontent.com/21287632/66109645-b3ef5480-e5f7-11e9-9c93-cb9711a101c8.png)

Finally found on of the problems, Go to CtxClient.cs line 540, set param.Add("debit", 0); from 0 to 1
