### ISSUE TITLE
Wrong parameter name (key): license_id -> license

### ISSUE THREAD

**Issue by mvidaldp** [Emotiv/cortex-v2-example#56]
https://github.com/Emotiv/cortex-v2-example/blob/2a3a91440a02f1fb3d43dca861f1c893ad444f24/python/lib/cortex.py#L202

The right parameter name (key) is license, not license_id. So:

params['license'] = license_id

**Comment by nguoithichkhampha** [comment]
thanks @mvidaldp we will update.

**Comment by nguoithichkhampha** [comment]
fixed in #57
