### ISSUE TITLE
Being able to train in another profile

### ISSUE THREAD

**Issue by Aniruddha008** [Emotiv/cortex-v2-example#58]
For some reason I am able to train lift command in another user's profile after physically selecting the profile in EmotivBCI. Hows that possible?
Has anybody faced that issue?
How many minimum trainings are required to close this issue?

**Comment by bchaperon** [comment]
Sorry @Aniruddha008 but I don't understand your issue.
What are you trying to do exactly?
What API method do you call, and what error message do you get?
