### ISSUE TITLE
Receiving data much faster than expected 

### ISSUE THREAD

**Issue by sohilkaushal** [Emotiv/cortex-v2-example#60]
Hello team Emotiv, 
Recently I and a couple of my friends were working with the API V2 and we noticed that the API sends data at a much faster rate than expected for power bands and it would be great if you could take a look at it

**Comment by bchaperon** [comment]
Hi @sohilkaushal 
You should receive the band power data at 8 hertz.
https://emotiv.gitbook.io/cortex-api/data-subscription
What frequency do you actually get? And what frequency do you expect?

**Comment by o7706111** [comment]
Can I change rate frequency of band power? If i can,please tell me by simple way. I am not good at English.

**Comment by bchaperon** [comment]
No, you cannot change the frequency. It is always 8 hertz.
