### ISSUE TITLE
Setting up with Unity

### ISSUE THREAD

**Issue by Paulhb7** [Emotiv/cortex-v2-example#65]
Hello, 
As I am a beginner in Unity and C#, I would like to know how it was possible to setup Cortex in Unity.
Thanks !

**Comment by nguoithichkhampha** [comment]
@Paulhb7 , cortex run as the service so, you don't need setup anything. To develop your app in Unity, you can try refer our C# example. The basic idea is create a socket client in Unity and connect to Cortex.

**Comment by Paulhb7** [comment]
Thanks ! I'll try it
