### ISSUE TITLE
Question: How is the pow stream computed from the EEG ?

### ISSUE THREAD

**Issue by nathanLaubeuf** [Emotiv/cortex-v2-example#66]
Everything is in the title. What are the bands (in Hz) that you use ? what is you extraction method ? On what time window are you extracting it ? Couldn't find anything in the API documentation.

**Comment by nguoithichkhampha** [comment]
Hi @nathanLaubeuf , actually we are using hanning windows with size 2 seconds to calculate the band in the frequency 4.0 to 45.0 Hz.
