### ISSUE TITLE
Question: Where is the rest of the code for the mental command example? pls help

### ISSUE THREAD

**Issue by ChaosLeon19** [Emotiv/cortex-v2-example#67]
Hello I run the mental command example and now i try to understand it.
But for me the project "mental command" only consists of a main where it says "dse.start ..." so I wonder where the rest of the code is where it says that it should issue the mental commands in the console or that he should stop the stream after a certain time. Where is this part of the code?

**Comment by nguoithichkhampha** [comment]
@ChaosLeon19 , mental command C++ example base on this class
https://github.com/Emotiv/cortex-v2-example/blob/master/cpp-qt/cortexclient/DataStreamExample.cpp
